services:
  mariadb:
    container_name: mariadb
    build:
      context: "./requirements/mariadb"
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    build:
      context: "./requirements/wordpress"
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: "./requirements/nginx"
      dockerfile: Dockerfile
    hostname: localhost
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
  
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis/
      dockerfile: Dockerfile
    volumes:
     - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  # redis:
  #   container_name: redis
  #   build:
  #     context: ./requirements/bonus/redis
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - wordpress:/var/www/wordpress
  #   networks:
  #     - inception

  ftp:
      container_name: ftp
      build:
        context: ./requirements/bonus/ftp
        dockerfile: Dockerfile
      ports:
        - "21:21"
        - "21100-21110:21100-21110"
      volumes:
        - "wordpress:/var/www/wordpress"
      networks:
        - inception
      restart: always
      env_file: .env


  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer:42
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - inception
    restart: always

  # adminer:
  #   build: ./requirements/bonus/adminer
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   expose:
  #    - "9000"
  #   networks:
  #     - inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jdoukhan/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jdoukhan/data/wordpress

networks:
  inception:
    driver: bridge